export const GET_MY_PO_LIST="GET_MY_PO_LIST";
export const GET_SINGLE_PO_DETAILS="GET_SINGLE_PO_DETAILS";
export const IS_PAGE_LOAD = "IS_PAGE_LOAD";
export  const GET_LATEST_PO = 'GET_LATEST_PO'
export  const GET_FAV_PO = 'GET_FAV_PO'
export  const UPDATE_CURRENT_ROLE = 'UPDATE_CURRENT_ROLE'
export  const IS_SINGLE_PO_DETAILS_DELETED = 'IS_SINGLE_PO_DETAILS_DELETED'
export  const GET_FILTERED_ORDER = 'GET_FILTERED_ORDER'
export  const GET_INVITED_USER_LIST = 'GET_INVITED_USER_LIST'
export  const IS_INVITED_USER_DELETED = 'IS_INVITED_USER_DELETED'
export  const GET_PAYMENT_VERIFICATION = 'GET_PAYMENT_VERIFICATION'
export  const CHANGE_GENERAL_INFO = 'CHANGE_GENERAL_INFO'
export  const GET_PO_ID = 'GET_PO_ID'
export  const GET_OFFER_DETAILS = 'GET_OFFER_DETAILS'
export  const GET_GROUP_CHAT = 'GET_GROUP_CHAT'
export  const CHANGE_ATTACHMENT_DATA ='CHANGE_ATTACHMENT_DATA'
export  const CHANGE_ITEM_INFO ='CHANGE_ITEM_INFO'
export  const GET_CATEGORY_INFO ='GET_CATEGORY_INFO'
export  const CHANGE_OFFER_INFO ='CHANGE_OFFER_INFO'


