export const CHANGE_USER_TYPE_INPUT = "CHANGE_USER_TYPE_INPUT";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const CHANGE_MANAGE_PROFILE_INPUT = "CHANGE_MANAGE_PROFILE_INPUT";
export const IS_PAGE_LOAD = "IS_PAGE_LOAD";
export  const GET_INVITED_USER_LIST = 'GET_INVITED_USER_LIST'
export  const IS_INVITED_USER_DELETED = 'IS_INVITED_USER_DELETED'
